In [2]:
def func():
    a = []
    for i in range(5):
        a.append(i)

In [3]:
a = []

def func():
    for i in range(5):
        a.append(i)

In [4]:
a = None

def bind_a_variable():
    global a
    a = []

bind_a_variable()

a

[]

In [5]:
def f():
    a = 5
    b = 6
    c = 7
    return a, b, c

In [6]:
a, b, c = f()

In [7]:
print(a, b ,c)

5 6 7


In [8]:
return_value = f()

In [9]:
return_value

(5, 6, 7)

### 3.2.3 함수도 객체다(p115)

In [10]:
states = ['Alabama ', 'Georgia! ', 'Georgia', 'georgia', 'FlOrIda', 'southcarolina##', 'West virginia?']

In [11]:
import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]', '', value)
        value = value.title()
        result.append(value)
    
    return result

In [12]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'Southcarolina',
 'West Virginia']

In [13]:
def remove_punctuation(value):
    return re.sub('[!#?]', '', value)

clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result

In [14]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'Southcarolina',
 'West Virginia']

In [15]:
for x in map(remove_punctuation, states):
    print(x)

Alabama 
Georgia 
Georgia
georgia
FlOrIda
southcarolina
West virginia


### 3.2.4 익명 함수

In [16]:
def short_function(x):
    return x * 2

equiv_anon = lambda x: x * 2

In [17]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

In [18]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']

In [19]:
strings.sort(key = lambda x: len(set(list(x))))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

### 3.2.6 제너레이터

In [20]:
some_dict = {'a' : 1, 'b' : 2, 'c' : 3}

for key in some_dict:
    print(key)

a
b
c


In [21]:
dict_iterator = iter(some_dict)
dict_iterator

In [22]:
list(dict_iterator)

['a', 'b', 'c']

In [23]:
def squares(n=10):
    print('Generating squares from 1 to {0}'.format(n ** 2))
    for i in range(1, n + 1):
        yield i ** 2

In [24]:
gen = squares()
gen

<generator object squares at 0x000001A5950E3AC0>

In [25]:
for x in gen:
    print(x, end = ' ')

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [26]:
gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x000001A5950F12E0>

In [27]:
def _make_gen():
    for x in range(100):
        yield x ** 2

gen = _make_gen()

In [28]:
sum(x ** 2 for x in range(100))

328350

In [29]:
dict((i, i ** 2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

### itertools 모듈

In [30]:
import itertools

first_letter = lambda x : x[0]

names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']

for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


## 4.1 Numpy ndarray : 다차원 배열 객체

In [31]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[-1.1948918 , -0.31922722, -0.92898838],
       [-0.6590144 , -0.47245716,  0.24443398]])

In [32]:
data * 10

array([[-11.94891796,  -3.19227222,  -9.28988382],
       [ -6.59014401,  -4.72457157,   2.44433981]])

In [33]:
data + data

array([[-2.38978359, -0.63845444, -1.85797676],
       [-1.3180288 , -0.94491431,  0.48886796]])

In [34]:
data.shape

(2, 3)

In [35]:
data.dtype

dtype('float64')

### 4.1.1 ndarray 생성하기

In [36]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [37]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr2.ndim

2

In [39]:
arr2.shape

(2, 4)

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [43]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray의 dtype

In [44]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr1.dtype

dtype('float64')

In [45]:
arr2.dtype

dtype('int32')

### 4.1.5 불리언값으로 선택하기

In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [47]:
data

array([[-0.64538036, -0.98097763,  0.96808157,  0.78378022],
       [ 0.15600646,  0.95703696, -0.02962331,  0.10833056],
       [-0.16523881, -0.15604202,  0.31421707, -1.34791359],
       [ 0.70285168, -0.73554874, -0.71797115,  0.54313551],
       [-1.40007573,  0.6290785 , -0.08899643,  0.04788991],
       [ 1.18282817,  0.78638927,  0.77618985,  1.12813331],
       [-0.08301334, -0.29599275, -0.00520243,  0.74927652]])

In [48]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [49]:
data[names == 'Bob']

array([[-0.64538036, -0.98097763,  0.96808157,  0.78378022],
       [ 0.70285168, -0.73554874, -0.71797115,  0.54313551]])

In [50]:
data[names == 'Bob', 2:]

array([[ 0.96808157,  0.78378022],
       [-0.71797115,  0.54313551]])

In [51]:
data[names == 'Bob', 3]

array([0.78378022, 0.54313551])

In [52]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [53]:
data[~(names == 'Bob')]

array([[ 0.15600646,  0.95703696, -0.02962331,  0.10833056],
       [-0.16523881, -0.15604202,  0.31421707, -1.34791359],
       [-1.40007573,  0.6290785 , -0.08899643,  0.04788991],
       [ 1.18282817,  0.78638927,  0.77618985,  1.12813331],
       [-0.08301334, -0.29599275, -0.00520243,  0.74927652]])

### 4.1.6 팬시 색인

In [54]:
arr = np.empty((8, 4))
arr

array([[8.94586138e-312, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [8.45593933e-307, 5.02034658e+175, 1.02380666e+166,
        2.14578806e+184],
       [2.98170949e+179, 2.75109044e+180, 1.58662212e-076,
        5.19440054e-144],
       [3.59751658e+252, 1.46901661e+179, 3.75505006e+199,
        2.59027921e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [5.55506440e+170, 6.58870915e-066, 6.39969129e+170,
        9.85660851e+165],
       [2.59027856e-144, 2.59903818e-144, 5.58166869e-091,
        1.24716233e-047],
       [9.96356175e-043, 1.11475752e+261, 1.16318408e-028,
        2.97707521e+296]])

In [55]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [56]:
arr = np.arange(32)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [57]:
arr.reshape((8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### 4.1.7 배열 전치와 축 바꾸기

In [58]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [60]:
arr = np.random.randn(6, 3)
arr

array([[ 0.70527747,  1.66031406,  1.27061207],
       [-0.92814337, -1.60114237, -2.0398671 ],
       [ 1.25076077, -0.02959639,  0.31586462],
       [-0.75772902, -0.62790854,  2.40850419],
       [ 1.19116251, -0.56734033, -0.71736624],
       [-0.68017309, -0.18491265,  0.56108247]])

In [61]:
np.dot(arr.T, arr)

array([[ 5.37892576,  2.54581637,  0.12336777],
       [ 2.54581637,  6.0715125 ,  4.15730349],
       [ 0.12336777,  4.15730349, 12.50560358]])